
(define (problem problem1)
    (:domain
        travel-domain    
    )

		(:objects
        	user1
        	waypoint waypoint1 waypoint2 waypoint3 waypoint4 waypoint5 waypoint6 waypoint7 waypoint8
)
    
    (:init
        (= (total-score) 0)
        (= (current-time) 0)
        (= (end-time) 600)
        (user user1)
		(waypoint waypoint1)
		(= (score waypoint1) 2.1875)
		(= (duration waypoint1) 300)
		(waypoint waypoint2)
		(= (score waypoint2) 2.34375)
		(= (duration waypoint2) 60)
		(waypoint waypoint3)
		(= (score waypoint3) 1.84375)
		(= (duration waypoint3) 120)
		(waypoint waypoint4)
		(= (score waypoint4) 2.16666666667)
		(= (duration waypoint4) 60)
		(waypoint waypoint5)
		(= (score waypoint5) 2.5)
		(= (duration waypoint5) 120)
		(waypoint waypoint6)
		(= (score waypoint6) 2.33333333333)
		(= (duration waypoint6) 120)
		(waypoint waypoint7)
		(= (score waypoint7) 2.75)
		(= (duration waypoint7) 60)
		(waypoint waypoint8)
		(= (score waypoint8) 2.66666666667)
		(= (duration waypoint8) 120)
		(= (drive-time waypoint1 waypoint2) 0 )
		(= (drive-time waypoint2 waypoint1) 0 )
		(= (drive-time waypoint1 waypoint3) 0 )
		(= (drive-time waypoint3 waypoint1) 0 )
		(= (drive-time waypoint1 waypoint4) 0 )
		(= (drive-time waypoint4 waypoint1) 0 )
		(= (drive-time waypoint1 waypoint5) 0 )
		(= (drive-time waypoint5 waypoint1) 0 )
		(= (drive-time waypoint1 waypoint6) 0 )
		(= (drive-time waypoint6 waypoint1) 0 )
		(= (drive-time waypoint1 waypoint7) 0 )
		(= (drive-time waypoint7 waypoint1) 0 )
		(= (drive-time waypoint1 waypoint8) 0 )
		(= (drive-time waypoint8 waypoint1) 0 )
		(= (drive-time waypoint2 waypoint3) 0 )
		(= (drive-time waypoint3 waypoint2) 0 )
		(= (drive-time waypoint2 waypoint4) 0 )
		(= (drive-time waypoint4 waypoint2) 0 )
		(= (drive-time waypoint2 waypoint5) 0 )
		(= (drive-time waypoint5 waypoint2) 0 )
		(= (drive-time waypoint2 waypoint6) 0 )
		(= (drive-time waypoint6 waypoint2) 0 )
		(= (drive-time waypoint2 waypoint7) 0 )
		(= (drive-time waypoint7 waypoint2) 0 )
		(= (drive-time waypoint2 waypoint8) 0 )
		(= (drive-time waypoint8 waypoint2) 0 )
		(= (drive-time waypoint3 waypoint4) 0 )
		(= (drive-time waypoint4 waypoint3) 0 )
		(= (drive-time waypoint3 waypoint5) 0 )
		(= (drive-time waypoint5 waypoint3) 0 )
		(= (drive-time waypoint3 waypoint6) 0 )
		(= (drive-time waypoint6 waypoint3) 0 )
		(= (drive-time waypoint3 waypoint7) 0 )
		(= (drive-time waypoint7 waypoint3) 0 )
		(= (drive-time waypoint3 waypoint8) 0 )
		(= (drive-time waypoint8 waypoint3) 0 )
		(= (drive-time waypoint4 waypoint5) 0 )
		(= (drive-time waypoint5 waypoint4) 0 )
		(= (drive-time waypoint4 waypoint6) 0 )
		(= (drive-time waypoint6 waypoint4) 0 )
		(= (drive-time waypoint4 waypoint7) 0 )
		(= (drive-time waypoint7 waypoint4) 0 )
		(= (drive-time waypoint4 waypoint8) 0 )
		(= (drive-time waypoint8 waypoint4) 0 )
		(= (drive-time waypoint5 waypoint6) 0 )
		(= (drive-time waypoint6 waypoint5) 0 )
		(= (drive-time waypoint5 waypoint7) 0 )
		(= (drive-time waypoint7 waypoint5) 0 )
		(= (drive-time waypoint5 waypoint8) 0 )
		(= (drive-time waypoint8 waypoint5) 0 )
		(= (drive-time waypoint6 waypoint7) 0 )
		(= (drive-time waypoint7 waypoint6) 0 )
		(= (drive-time waypoint6 waypoint8) 0 )
		(= (drive-time waypoint8 waypoint6) 0 )
		(= (drive-time waypoint7 waypoint8) 0 )
		(= (drive-time waypoint8 waypoint7) 0 )
		(not ( visited user1 waypoint1) )
		(not ( visited user1 waypoint2) )
		(not ( visited user1 waypoint3) )
		(not ( visited user1 waypoint4) )
		(not ( visited user1 waypoint5) )
		(not ( visited user1 waypoint6) )
		(not ( visited user1 waypoint7) )
		(not ( visited user1 waypoint8) )
		(user-at user1 waypoint6) ) 

	(:goal
		(and
			(visited user1 waypoint1)
			(visited user1 waypoint2)
			(visited user1 waypoint3)
			(visited user1 waypoint4)
			(visited user1 waypoint5)
			(visited user1 waypoint6)
			(visited user1 waypoint7)
			(visited user1 waypoint8)

    	)
    )
    (:metric 
        maximize (total-score)         
    )
)
